/* Copyright (c) 2013 NITLab, University of Thessaly, Greece
 * This software may be used and distributed solely under the terms of the MIT license (License).
 * You should find a copy of the License in LICENSE.TXT or at http://opensource.org/licenses/MIT.
 * By downloading or using this software you accept the terms and the liability disclaimer in the License.
*/

package com.omf.resourcecontroller.OMF;

import org.jivesoftware.smackx.pubsub.LeafNode;
import org.jivesoftware.smackx.pubsub.Node;
import org.jivesoftware.smackx.pubsub.PayloadItem;
import org.jivesoftware.smackx.pubsub.SimplePayload;

import android.util.Log;

public class MessagePublisher {

	
	public static final String TAG = "MessagePublisher";
	
	/**
	 * Publish item
	 * @param xmlString : The xml string generated by the XMLGenerator
	 * @param SCHEMA : The OMF Schema
	 * @param mType : the OMF message type
	 * @param pubNode : the node for the mesage to be published
	 */
	public void PublishItem(String xmlString, String SCHEMA, String mtype, Node pubNode)
	{
		SimplePayload payload = new SimplePayload(mtype,SCHEMA, xmlString);

		@SuppressWarnings({ "unchecked", "rawtypes" })
		PayloadItem payloadItem = new PayloadItem(null, payload);
		
		Log.e(TAG, "Message Published to:"+pubNode.getId());
		
		((LeafNode)pubNode).publish(payloadItem);
			
	}
}
